### ISSUE TITLE
py3k branch missing

### ISSUE THREAD

**Issue by albertjan** [pypyjs/pypy#4]
Hey @rfk I opened an issue about this somewhere but I can't find it anymore. I just wanted to give a **very** gentle reminder that you were going to push the py3k branch for pypy to this repo. Thanks!

**Comment by jedie** [comment]
maybe: https://github.com/pypyjs/pypyjs/issues/60 ?

**Comment by albertjan** [comment]
Yeah but there's no way to build the py3 version atm.

**Comment by rfk** [comment]
Ugh, looks like I've somehow deleted the checkout where I had the py3k branch working, so I'll have to re-create that from memory.  I don't think there was anything too tricky about it, just need to sit down and go through the steps again.  Thanks for the reminder!

**Comment by NinTheNoodle** [comment]
I just realised that this project is the only reason I'm still using python 2 for my project. Any news on the python 3 build?

**Comment by rfk** [comment]
>  this project is the only reason I'm still using python 2

Oof, I'm sorry to hear that.  I've finally gotten around to taking another look at the build setup for a py3 version and I _think_ I've got it figured out again.  It'll probably take me a day or two to shake out the rough edges, but this shouldn't be far away.  Thanks for your patience all.

**Comment by albertjan** [comment]
@rfk you are awesome!

**Comment by rfk** [comment]
Some notes on what I'm doing, for reference:
- Make a copy of the upstream py3k branch, call it "pypyjs3"
- Port the changes to the `./pypy/` directory from our "pypyjs" branch over to "pypyjs3"; they're small and apply pretty cleanly
- Do _not_ port the changes from `./rpython`, they won't apply cleanly; instead just wholesale copy `./rpython` over from our "pypyjs" branch
- Build as normal

I'm going to leave it building and we'll see how it comes out.  Two things to follow up on, assuming it works:
- how much of the above procedure should we commit into github, vs how much to just do as part of the build?
- probably there will have to be some tweaking of the support code in `pypyjs.js` and friends from https://github.com/pypyjs/pypyjs

**Comment by albertjan** [comment]
the whole `/rpython` folder? or just the platform changes?

**Comment by rfk** [comment]
> the whole /rpython folder?

Yep, all of it; the upstream "py3k" branch is significantly different to the one that our "pypyjs" branch is currently tracking, so I haven't had much success with trying to apply any subset of the changes there.

**Comment by rfk** [comment]
(IIRC the pypy team has/had plans to split off that "rpython" directory into a completely stand-alone project anyway, which would greatly simplify things for us here)

**Comment by albertjan** [comment]
Lets hope they pick the version that works for us :smile:

**Comment by rfk** [comment]
Update: there's now a `pypyjs3` branch that tracks upstream `py3k` branch, with our customizations on top:

  https://github.com/pypyjs/pypy/tree/pypyjs3

I've got this building locally and mostly working, just figuring out some edgecases and the best way to script it up.  Hopefully I'll have something to push either this evening or tomorrow.

**Comment by rfk** [comment]
I've pushed my initial experiment with building a py3 version, see https://github.com/pypyjs/pypyjs/issues/60#issuecomment-151808467

I'm not super happy with the naming of the build targets, or anything here really - it's hard to convey version numbers for different things in a single name.  Suggestions for better naming most welcome.

**Comment by rfk** [comment]
I _think_, assuming the above works for anyone else besides me, that we can close this issue out here and follow up on a release in https://github.com/pypyjs/pypyjs/issues/60 or https://github.com/pypyjs/pypyjs/issues/172

**Comment by NinTheNoodle** [comment]
Wow, that was a lot faster than I expected. :) Thank you!

**Comment by albertjan** [comment]
@rfk thanks! I'm in the middle of a move so I can't try it out this week, very cool to see py3 support back :smile:. I'll close this issue.
